### ISSUE TITLE
lock.hcl together with used versions in required providers throw errors

### ISSUE THREAD

**Issue by cafecrema** [epomatti/azure-workload-identity-terraform#1]
Hi, 

thanks for your code! It helps me to implement workload identities. 

One thing I have to mention is, that with the hardcoded versions in azure -> in required providers and the terraform.lock.hcl in azure it stops after the terraform plan:  

`│ Error: expected "object_id" to be a valid UUID, got 
│
│   with azurerm_key_vault_access_policy.superadmin,
│   on main.tf line 112, in resource "azurerm_key_vault_access_policy" "superadmin":
│  112:   object_id = data.azurerm_client_config.current.object_id`

After removing the versions out of the providers block and removing of the .lock.hcl, it works without errors with the hashicorp/azuread v2.31.0 and hashicorp/azurerm v3.34.0 versions.

So the solution is to remove the lock files here.

Cheers,
Michael

**Comment by epomatti** [comment]
@cafecrema appreciate you putting some of my code to use and also for reporting the issues.

It looks like Terraform evolved and the code stopped working. I bumped to newer versions it is working as expected.
